### ISSUE TITLE
cannot use column

### ISSUE THREAD

**Issue by Fuchsoria** [flylink888/gorm-firebird#1]
`cannot use column (variable of type Column) as gorm.ColumnType value in argument to append: Column does not implement gorm.ColumnType (missing method AutoIncrement)`

Full missing methods are: 
func (c Column) AutoIncrement() (isAutoIncrement bool, ok bool)
func (c Column) ColumnType() (columnType string, ok bool)
func (c Column) Comment() (value string, ok bool)
func (c Column) DefaultValue() (value string, ok bool)
func (c Column) PrimaryKey() (isPrimaryKey bool, ok bool)
func (c Column) ScanType() reflect.Type
func (c Column) Unique() (unique bool, ok bool)

gorm.io/gorm v1.23.3
github.com/flylink888/gorm-firebird v1.0.2

**Comment by flylink888** [comment]
Only firdbird versions 3.0 and above are supported
