### ISSUE TITLE
ColumnType does not implement gorm.ColumnType

### ISSUE THREAD

**Issue by diorodrigu** [flylink888/gorm-firebird#2]
Hello, this problem occurs here

`github.com/flylink888/gorm-firebird
../../go/pkg/mod/github.com/flylink888/gorm-firebird@v1.0.2/migrator.go:6:2: could not import reflect (open : no such file or directory)
../../go/pkg/mod/github.com/flylink888/gorm-firebird@v1.0.2/migrator.go:210:38: cannot use ColumnType{…} (value of type ColumnType) as type gorm.ColumnType in argument to append:
	ColumnType does not implement gorm.ColumnType (missing DatabaseTypeName method)
../../go/pkg/mod/github.com/flylink888/gorm-firebird@v1.0.2/firebird.go:100:39: invalid operation: cannot indirect limit.Limit (variable of type int)`

good work

**Comment by diorodrigu** [comment]
resolved by downgrading the gorm to v1.22.3

**Comment by flylink888** [comment]
gorm v1.25.7 is supported
